version: '3.4'

networks:
  app-tier:
    driver: bridge
services:
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    ports:
     - '9092:9092'
     - '9094:9094'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false

  producerservice:
    image: ${DOCKER_REGISTRY-}producerservice
    networks:
      - app-tier
    build:
      context: .
      dockerfile: ProducerService/Dockerfile
    depends_on:
      - kafka

  consumerapp:
    image: ${DOCKER_REGISTRY-}consumerapp
    networks:
      - app-tier
    build:
      context: .
      dockerfile: ConsumerApp/Dockerfile

